### ISSUE TITLE
Use of after/ftplugin/

### ISSUE THREAD

**Issue by george-b** [romainl/vim-qf#102]
I'm wondering why `after/ftplugin/` is used rather than just `ftplugin/`? I would have thought plugins in generally would only use `after/ftplugin/` in order to be able to compose/override other plugins in a way that is complementary albeit somewhat naive.

**Comment by romainl** [comment]
`after/ftplugin/$FILETYPE.vim` is sourced last so it is the ideal place for adding things without having to rewrite the whole `$VIMRUNTIME/ftplugin/$FILETYPE.vim` or for partially overriding things defined in that file.

**Comment by george-b** [comment]
But there's nothing contentious with the runtime in this plugin is there?

**Comment by romainl** [comment]
> But there's nothing contentious with the runtime in this plugin is there?

Sorry but I don't understand your question.

**Comment by romainl** [comment]
> Is there anything `$VIMRUNTIME/ftplugin/qf.vim` that interferes or require it be sourced before anything in this plugin?

It's just the default ftplugin, which I have no need or desire to rewrite. If something is added to it in the future, I don't want my plugin to break it unknowingly.

The "after" mechanism has nothing to do with plugin composition. Its only purpose is to allow the user to augment and/or override default settings.

**Comment by george-b** [comment]
OK I'm going to go a bit off track if you'll entertain me. Why is the default runtime sourced after plugins? I agree it would seem logical that plugins should get sourced after the default runtime. My assumption would be that things in the default runtime typically have guards around them and thus can be prevented from loading which is useful as Vim doesn't have a way to truly unload things. If the after directory in plugins is not intended for composition then it just seems like a race to the bottom, one which cannot knowingly be won. The more I think about this the more I think the only after directory Vim should consider is `~/.vim/after`...

I think this has turned into a more philosophical matter, feel free to close.

**Comment by romainl** [comment]
> If the after directory in plugins is not intended for composition then it just seems like a race to the bottom, one which cannot knowingly be won.

That's what you get when you just add stuff to stuff without giving much thought to the overall design.

That's also why I am—discreetly, admittedly—advocating for a proper plugin API that would give plugin developers composition, etc. and users more confidence in their config.

Consider plugin `pastrami` exposing all its feature under a `pastrami` namespace, with mappings having clear attributes like `isLocalToWindow`, `acceptsCount`, `isCompatibleWith`, etc. Now consider plugin `bagel` exposing its own features under the `bagel` namespace, including a mapping that is composable with any other mapping with a truthy `acceptsCount`. Those examples are of course for illustration purpose only, but I think the idea has potential.

What I would really like to see is a clearer separation of concern between configuration, the kind of things users are expected to put in their `vimrc` like `set ...`, `nnoremap ...`, and proper plugin development, which would be a fully programmatic endeavour: `call setOpt('foo', 1, 0)` versus `set foo=1`, `call createMap({"lhs": '<F5>', ...` versus `nnoremap <F5> ...`, etc. (again pseudocode for illustration only).

**Comment by george-b** [comment]
Oh yeah I fully agree with that, as I mentioned in my initial comment I think the after directory is "naive".
