### ISSUE TITLE
qf_mapping_ack_style does not respect qf_window_bottom

### ISSUE THREAD

**Issue by jandamm** [romainl/vim-qf#107]
Both `p` and `s` would place the new window below the Quickfix window.

These mappings did work for me:
```vim
nnoremap <silent> <buffer> p :call qf#preview#PreviewFileUnderCursor()<CR><C-w>J
nnoremap <silent> <buffer> s <C-w><CR><C-w>p<C-w>J<C-w>p
```
(Basically just adding `<C-w>J`)

**Comment by romainl** [comment]
I guess we can make it check `g:qf_window_bottom` before doing `<C-w>J`.

**Comment by jandamm** [comment]
Definitely.
Should I create a PR?

**Comment by romainl** [comment]
@jandamm Please do.

**Comment by jandamm** [comment]
I've created a PR for this.
Turned out it was only related to `splitbelow`.
