### ISSUE TITLE
Remove doc/tags file from the repo

### ISSUE THREAD

**Issue by zealotrush** [romainl/vim-qf#119]
Could you please remove the doc/tags file from the repository? After I run the `:helptags ALL` command in Vim, this repo got dirty due to the updated tags file.

**Comment by romainl** [comment]
Since 8.1 and the introduction of `:help package`, it is recommended that plugin developers distribute documentation tags with the rest:

    Run the `:helptags` command to generate the doc/tags file.  Including this
    generated file in the package means that the user can drop the package in the
    pack directory and the help command works right away.

**Comment by zealotrush** [comment]
Thanks about the information about `:help package`. I didn't know that. However, could please make sure that the tags file is up to date? I cloned the latest repo, then run `:helptags ALL`, I got this diff result:

```diff
$ git diff
diff --git a/doc/tags b/doc/tags
index ee5a502..550b04f 100644
--- a/doc/tags
+++ b/doc/tags
@@ -35,10 +35,6 @@
 <Plug>(qf_qf_switch)   qf.txt  /*<Plug>(qf_qf_switch)*
 <Plug>(qf_qf_toggle)   qf.txt  /*<Plug>(qf_qf_toggle)*
 <Plug>(qf_qf_toggle_stay)      qf.txt  /*<Plug>(qf_qf_toggle_stay)*
-QfHistoryNewer qf.txt  /*QfHistoryNewer*
-QfHistoryOlder qf.txt  /*QfHistoryOlder*
-QfNextFile     qf.txt  /*QfNextFile*
-QfPreviousFile qf.txt  /*QfPreviousFile*
 qf     qf.txt  /*qf*
 qf-acknowledgements    qf.txt  /*qf-acknowledgements*
 qf-configuration       qf.txt  /*qf-configuration*
```

**Comment by romainl** [comment]
Thank you for reporting this. The `tags` file is now up-to-date.
