### ISSUE TITLE
Open and Close Quickfix changes others windows size

### ISSUE THREAD

**Issue by MaikoID** [romainl/vim-qf#12]
Hey, I'm currently with this problem using this plugin,  could you guys reproduce? Maybe is my environment.

Thx

**Comment by romainl** [comment]
Hi, could you be a bit more specific?

**Comment by blueyed** [comment]
It is related to https://github.com/vim/vim/issues/931 I think.

@MaikoID 
You can disable it using:
```vim
let g:qf_loclist_window_bottom = 0
let g:qf_window_bottom = 0
```

@romainl 
I could imagine doing this only if necessary, i.e. there is a window below or next to it?!
These could be detected using the following (just for "below"):

```vim
  let windows_above = []
  while 1
    let w = winnr()
    noautocmd wincmd k
    if w == winnr()
      break
    endif
    let windows_above += [winnr()]
  endwhile
```

**Comment by blueyed** [comment]
And as for `qf_loclist_window_bottom` I would say a default of `0` seems more sensible in general - at least I like to have the location list windows with their window.

**Comment by MaikoID** [comment]
Hey @blueyed applying your suggestions seems to work, thanks.

Sorry I'm was very busy at the moment and couldn't  elaborate the question, many thanks for your patience =)

bye

**Comment by blueyed** [comment]
@romainl 
Do you think we should change the defaults and/or improve the behavior to work around Vim resizing windows unnecessarily?!

**Comment by romainl** [comment]
@blueyed I think changing the defaults would be a better idea. I defined them as I want them but you are right that `0` would be a better default value.
