### ISSUE TITLE
Allow configuring highlight groups

### ISSUE THREAD

**Issue by savchenko** [romainl/vim-qf#122]
There are `qfFileName` and `qfLineNr`, but I seemingly can't set the highlight of the current line without overwriting both:

![image](https://user-images.githubusercontent.com/300146/130616378-da1a9719-ffe6-4cfe-84a4-bdc8ec678720.png)

Being able to define something like `qfCurLine` in user's theme file would be great.

**Comment by romainl** [comment]
Hmm… I have no idea what that screenshot is supposed to demonstrate. It looks perfectly fine to me. Could you be more specific about what you are trying to achieve and the problems you are facing?

**Comment by savchenko** [comment]
I don't see a way to change the highlight of the selected line with the available highlight groups.
I propose to introduce a new highlight group so that user can adjust it on their end.

_(...after a bit of research...)_

Shall try https://stackoverflow.com/questions/60589935/vim-change-highlight-of-current-quickfix-line-quickfixline, will reply here.

**Comment by romainl** [comment]
The line on which the cursor is is highlighted with `CursorLine` and the line of the current error is highlighted with `Search`. I'm not sure what more you need.

Good luck anyway.

**Comment by savchenko** [comment]
Turns out `QuickFixLine` does the job and by skipping `fg/bg` it is possible to overload its attribute, for example with bold or italic.

Sorry about the noise.
