### ISSUE TITLE
need ToggleList feature

### ISSUE THREAD

**Issue by vbauerster** [romainl/vim-qf#13]
It is very useful plugin, but lacks ToggleList feature.
Could you please implement Quick/Location list toggle mappings, like:
`<Plug>QfCtoggle`
`<Plug>QfLtoggle`

At first I tried to apply [this]( http://vim.wikia.com/wiki/Toggle_to_open_or_close_the_quickfix_window) solution, but it relies on output of :ls to have quickfix buffers.

If it is too much work, so I'd like to have at least two functions available, (which user can call):
`qf#IsCopen`
`qf#IsLopen`

**Comment by ntnn** [comment]
I've already worked on that: https://github.com/ntnn/vim-qf/tree/toggle-window
It works well, but the major problem is the time copen/cclose need (takes ~1 or 2s).

iirc there was a recent patch adding more qf/loclist information functions, might be able to provide a toggle-map using those.

**Comment by romainl** [comment]
I just pushed a preliminary version in the "toggle-windows" branch. The whole thing is pretty instantaneous, here, but `qf#ToggleLocWindow()` needs a bit more love.

We are almost there.

Also, I prefer @vbauerster's names to the ones I used.

**Comment by vbauerster** [comment]
Glad to hear that) Thank you!
Btw, I think even 1-2s to copen/cclose is acceptable.
PS: I'm neovim user.

**Comment by romainl** [comment]
Please take a look at the "toggle-windows" branch. I'm quite satisfied of how `<Plug>QfLtoggle` works, now. Tell me if you have any issue.

**Comment by ntnn** [comment]
I changed `qf#IsQfWindow` like we discussed in IRC to return `true` only
for an actual qf window and reordered `qf#ToggleLocWindow` to look a bit
nicer (essentially all that was needed was to move the `else` statement
up and eliminate the if around it with an early return. The rest is
similar to `qf#ToogleQfWindow`.

With a bit of modifications it might be possible to cram both functions
into one, but I think it'd get harder to maintain and gain a lot of
unnecessary complexity.

Also, L35-41 and L80-84 - iirc window numbers are global, so in
`qf#ToggleQfWindow` might fail when another tab has a qf window opened
and `qf#ToggleLocWindow` could fail when multiple windows have
a location window open - or am I missing something?

**Comment by ntnn** [comment]
Sorry for the double post, put github's specul js doesn't let me do anything again.
Here's the link to the working branch: https://github.com/ntnn/vim-qf/tree/toggle-windows

**Comment by ntnn** [comment]
Ye, nvm what I wrote above - i forgot that window numbers are tablocal
and reordered instead of filled up.

However I mentioned another problem - when multiple windows have
a loclist and you're trying to open the loc window of a window where the
index is lower `qf#ToggleLocWindow` will attempt to execute `:lclose`.

I'd say for location windows it's reasonable to assume that the location
list always has the index `winnr() + 1`, seein how vim manages windows.

I'm writing something on a separate branch on it.

**Comment by romainl** [comment]
Toggling is now part of vim-qf as of version 0.0.9.
