### ISSUE TITLE
Deprecate or alias :Dofile and :Doline 

### ISSUE THREAD

**Issue by nelstrom** [romainl/vim-qf#2]
Good news! [Patch 7.4.858](https://github.com/vim/vim/commit/aa23b379421aa214e6543b06c974594a25799b09) adds native `:cdo`, `:cfdo`, `:ldo`, and `:lfdo` commands. You can either remove the `:Dofile` and `:Doline` from this plugin, or simply redefine them as aliases to the built-in commands. (Admittedly, `:cfdo` doesn't exactly roll of the tongue!)

**Comment by romainl** [comment]
Hi! I won't remove those commands because I don't follow Vim's patch cycle very closely and I will certainly not require my users to run a specific patch.

But the aliasing idea is great. I'll add that this week end.

Thanks for the suggestion.

**Comment by nelstrom** [comment]
Yeah, it would be good to do it so that `:Dofile` and `:Doline` are available as an alias for people using 7.4.858+ and use your own implementation as a 'polyfil' for people using older versions of Vim.

**Comment by nelstrom** [comment]
I don't enjoy telling people 'this feature is available if you're using Vim 7.4.858 or greater'. But on the other hand, with the patch numbers getting so high, it's likely we'll see version 7.5 before too long, and I don't mind saying 'this feature is availabe in Vim 7.5'.

**Comment by romainl** [comment]
Hi, Drew.

Commit FA5DE63 seems to work here. Or does it?

**Comment by romainl** [comment]
Fixed as of fa5de631b9af3fc1b11f736f2147ca0c1aa44c4c.
