### ISSUE TITLE
location list toggling is half-broken

### ISSUE THREAD

**Issue by romainl** [romainl/vim-qf#20]
On branch refactoring-time, toggling the location list only works from the location window and not from the parent window.

**Comment by ntnn** [comment]
That is quite weird. It seems the problem stems from ``qf#IsLocWindow``, however when I execute that by hand it seems to work correctly.

**Comment by ntnn** [comment]
Found the bug. There is no window 0, but we're iterating in L81 from 0 to ``winnr('$')`` which results in ``[0, 1]``, which doesn't reach the window 2, assuming that only one window and locwin are opened.

**Comment by ntnn** [comment]
It also only affected the locwin because ``qf#IsQfWindow`` is called with ``+1``. I'll apply that for ``ToggleLocWindow`` as well.

**Comment by ntnn** [comment]
Fixed with d5b2db6.
