### ISSUE TITLE
Provide methods to jump to the previous/next errors from the cursor

### ISSUE THREAD

**Issue by blueyed** [romainl/vim-qf#28]
ALE has some nice functions to jump to the previous/next (nearest) entries in the location list, based on the cursor position: https://github.com/w0rp/ale/blob/master/autoload/ale/loclist_jumping.vim

Do you think something like this makes sense to have in vim-qf, so that it can be used in general, and not only when using ALE?

/cc @w0rp

**Comment by w0rp** [comment]
If the loclist jumping I wrote is changed to use a sequential search instead of a binary search, then it could work in combination with any plugin. It has to be changed to sequential search if it's not specific to ALE, because we can't assume that the list is sorted any more.

**Comment by romainl** [comment]
Yes, this totally makes sense and doesn't sound too hard to implement.

**Comment by romainl** [comment]
What would be the behavior of the command when the closer location/error is the current line?

* Jump to the next closer one?
* NOP?

**Comment by blueyed** [comment]
In general it should also take columns into account.
But in general (for the same line or line+col), it should go to the next one.

**Comment by infokiller** [comment]
@blueyed this may be useful for you: https://github.com/infokiller/vim-errorlist

**Comment by blueyed** [comment]
@infokiller 
Thanks.  There are commands in Vim for this by now (`:cbefore` etc), and a WIP PR to merge them to Neovim: https://github.com/neovim/neovim/pull/11119

**Comment by infokiller** [comment]
@blueyed oh no, I could have avoided writing that plugin!
Thanks for letting me know!

**Comment by infokiller** [comment]
@blueyed reading the docs and playing with the new commands in my vim installation (8.1 1-2102), it seems that a plugin is still needed for the following:
- Supporting wrap around
- Jumping to the next buffer when in the last error of the current buffer
- Supporting lists of errors that are not sorted by their buffer number
- Navigating multiple errors in the same line

Reference docs for `:cabove`:

```
:[count]cabo[ve]	Go to the [count] error above the current line in the
			current buffer.  If [count] is omitted, then 1 is
			used.  If there are no errors, then an error message
			is displayed.  Assumes that the entries in a quickfix
			list are sorted by their buffer number and line
			number. If there are multiple errors on the same line,
			then only the first entry is used.  If [count] exceeds
			the number of entries above the current line, then the
			first error in the file is selected.
```

**Comment by romainl** [comment]
Looks like no work is necessary on this one after all.
