### ISSUE TITLE
Provide an option to control qf auto-sizing

### ISSUE THREAD

**Issue by comand** [romainl/vim-qf#34]
I use skywind3000/asyncrun.vim to invoke make for my project and list the output in the quickfix window. Because vim-qf auto-sizes the quickfix window when it is toggled open, and when it does open there are typically only one or two lines of build output available, I always end up with a quickfix window that's 3 or 4 characters high, and I have to either toggle it open/closed manually to get it to resize once more output is available, or somehow manually resize the window so I can see my output.

It would be great to have an option to make the qf window a fixed size always, or to turn off the auto-scaling entirely, so I could set it to a particular size once in the session, then toggle it open and closed at that size.

Otherwise, I'm really loving this plugin -- nice work!
- C.

**Comment by comand** [comment]
Another use case -- sometimes I have my qf open to a height greater than the default 10 lines so I can see more of my build output. When I re-run the build, it tries to re-toggle open the quickfix, which forces the size down to 10 lines. If the qf window is open, qf toggling it open shouldn't cause a resize.

**Comment by romainl** [comment]
This sounds like a very reasonable request. I will work on it today.

**Comment by romainl** [comment]
Please tell me what you think about this:

'g:qf_max_height'
Value: numeric
Default: none

The maximum height of location/quickfix windows.

With a value of `0`:

    let g:qf_max_height = 0

    - If there is no existing location/quickfix window, the height of the
      new window is adjusted to the lesser of those numbers: the number of
      items in the list or `10`, Vim's default.
    - If we are refreshing an existing window, its height is not adjusted.

    This gives the user the most flexibility: the initial height of the window
    is optimized within Vim's default constraints but further manual resizing,
    if any, is respected when refreshing the content.

With a value superior to `0`:

    let g:qf_max_height = 8

    - The height of location/quickfix windows is adjusted to the lesser of
      those numbers: the number of items in the list or |g:qf_max_height|.

    This gives the user the most control: the window height is relative to its
    content within user-defined constraints.

With no value (default behavior):

    - The height of location/quickfix windows is adjusted to the lesser of
      those numbers: the number of items in the list or `10`, Vim's default.

    This gives the user the most predictability: the window height is relative
    to its content within Vim's default constraints.

**Comment by comand** [comment]
That sounds great -- I'd be happy to test this out whenever you have something to test drive.

Thanks!
- C.

**Comment by romainl** [comment]
@comand could you take commit #639796d for a ride?

**Comment by comand** [comment]
Hmm... it's not exactly what I was imagining. Here's how it's working for me now, with:

let g:qf_max_height = 10

When a new asyncrun job starts up, qf is cleared and the async job starts writing output to the quickfix window. At job start, vim-qf resizes the window to 3 lines, which is the number of lines output by the job as it starts up. As more input is written to the qf window by the job, the height of the qf window increases until it reaches my qf_max_height. If I manually change the size of the quickfix (by dragging the window split with my mouse), then start a new build, the qf window jumps back down to 3 lines again and grows to qf_max_height.

What I would really love is that I could set a fixed height for the qf window when vim-qf toggles it open. That could be accomplished by having both a qf_max_height and a qf_min_height (or just a qf_fixed_height). Ideally, if the user changes the size of the split manually, vim-qf could remember that for the session and use the new fixed height.

When I'm using the quickfix in this way, I always know that my output is going to be about the same size or larger, so I'm looking to keep my windows from jumping around as the qf split size changes.

Hope that's helpful -- thanks for looking at this!
- C.

**Comment by romainl** [comment]
I just installed asyncrun and tried it with various `:AsyncRun ag ...` from `~/.vim/`.

Without setting `g:qf_max_height`, I get a 10 lines tall window on first run and no resizing whatsoever during following runs (I will probably add an autocommand for that). Vim-qf's `:Keep`, `:Reject`, and `:Restore` still resize the window as expected and the height of the window is respected after a manual resize.

![34-default](https://cloud.githubusercontent.com/assets/344335/22669855/d62dda12-ecc6-11e6-81b7-9f168a4a0658.gif)

---

With `g:qf_max_height = 7`, I get the same behavior as above but with a maximum of 7 lines instead of 10.

![34-7](https://cloud.githubusercontent.com/assets/344335/22669902/01a82422-ecc7-11e6-9e2b-086eb5c11f81.gif)

---

With `g:qf_max_height = 0`, I get a 10 lines tall window on first run but as soon as the window is resized manually no further change in the content of the window is able to change the height I've set manually. This behavior is what I thought you wanted.

![34-0](https://cloud.githubusercontent.com/assets/344335/22669966/5b455ec8-ecc7-11e6-9b84-ca6cae7e7b94.gif)

---

Now it seems to me that you want a cross between `7` and `0`. Could you add a screen capture to the thread?

**Comment by comand** [comment]
Here's a capture that demonstrates the behavior I'm seeing:

![vimqf](https://cloud.githubusercontent.com/assets/429986/22707584/15138a54-ed28-11e6-8795-228a68a9689f.gif)

The test script I'm running is this:

```
#!/bin/sh

for i in {1..20}
do
    sleep .25
    echo "output:$i:0: the current time is $(date)"
done
```

I suspect that the behavior you're showing above might have to do with the speed at which the quickfix window fills up. Asyncrun checks for output on a timer, which I believe defaults to 100ms. If your command outputs more than qf_max_height/default lines inside of the 100ms window, you don't see the jumping or growing window that I do.

Hope this is helpful,
 - C.

**Comment by romainl** [comment]
The more I think about it the more I think you actually want automatic resizing to be optional.

**Comment by comand** [comment]
It would be fantastic if I could set something that would disable autosizing altogether.

**Comment by romainl** [comment]
This will be a lot easier to implement than trying to achieve consensus on an advanced behavior of autosizing :-)

This will be fixed during the week-end.

**Comment by romainl** [comment]
Discussion moved to issue #37.
