### ISSUE TITLE
Respect foldopen setting

### ISSUE THREAD

**Issue by robertmeta** [romainl/vim-qf#4]
Example: \<Plug\>QfCprevious does not respect the foldopen setting, so while :cprevious will hop to previous item and open the fold, <Plug>QfCprevious will hop and leave the fold closed, regardless of the foldopen setting.

**Comment by romainl** [comment]
@robertmeta, could you give the latest commit a try?

**Comment by robertmeta** [comment]
Sweet, works properly now!
