### ISSUE TITLE
Configurable: "quit Vim if the last window is a location/quickfix window"

### ISSUE THREAD

**Issue by Asheq** [romainl/vim-qf#42]
Could you make this behavior configurable by the user?

I'm thinking of an options/setting called `qf_autoquit_vim`

The default value of this setting could be true. I would personally set it to false for myself, so I don't accidentally quit vim when I'm being sloppy with my fat fingers :P Thanks

**Comment by romainl** [comment]
The option is on `master`, it is called `g:qf_auto_quit`. Thank you.
