### ISSUE TITLE
Error while processing function qf#wrap#wrapCommand when the swap file already exists

### ISSUE THREAD

**Issue by mdsn** [romainl/vim-qf#43]
If the quickfix list navigation makes vim open a file that already has a swap file, after selecting what to do (edit anyway, delete, etc) the following error comes up:

> Error detected while processing function qf#wrap#WrapCommand:
> line   10:
> E325: ATTENTION

How to reproduce: go into an empty directory, write the same string to a few files. Open all of them in vim, then kill the instance from a separate shell. Open vim in the same directory and grep for the previous string. Navigate the results on the qf list and try to edit or delete the files, error should come up.

Version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb  6 2017 16:10:01)

**Comment by romainl** [comment]
Please try branch `issue#43`.

**Comment by mdsn** [comment]
@romainl that solves it. Thanks

**Comment by romainl** [comment]
Good to hear. Branch `issue#43` is now merged into `master`. Thanks for using vim-qf.
