### ISSUE TITLE
`wincmd p` is not conflicts with some extensions

### ISSUE THREAD

**Issue by guiniol** [romainl/vim-qf#45]
When opening the quickfix window, `vim-qf` does a `wincmd p` to come back to the previous window. This conflicts with some extensions which already do a `wincmd p` after populating the quickfix window (`vimtex` in my case). My current solution is to disable `vim-qf`'s auto-open, but that means I lose useful functionalities such as auto-resize. I'm not sure if there's a good solution, but if there was a way to check if we're on the quickfix window before doing the `wincmd p` that would help.

cc @lervag because if there's a way to check, then it should probably be in `vimtex` too?

**Comment by lervag** [comment]
@guiniol In vimtex, you can control the behaviour with `g:vimtex_quickfix_mode` (see docs). Set it to 1 to avoid the `wincmd p` from vimtex.

**Comment by guiniol** [comment]
@lervag Maybe I'm wrong in thinking it's a double `wincmd p` then, I tried setting `g:vimtex_quickfix_mode` to 1, and the quickfix window still gets the focus (actually, setting it to 0 or 2 doesn't change anything either). I did check the doc the other day and tried that, but I wasn't sure what the setting did exactly behind the scene. I'm sure it was working fine before the update on friday, but I can't say which version I was using before that of either `vim-qf` or `vimtex`...

**Comment by lervag** [comment]
@guiniol I propose that you create a minimal example. If this is only a vimtex problem, please open an issue on the vimtex page. If the issue is related to a problem with combining vim-qf with vimtex, then we'll continue the discussion here.

If I understand your original description, the issue is only reproducible when you combine vim-qf with vimtex. But based on your last comment, it feels like the problem could be pure vimtex.

By defining a minimal vimrc file and a minimal tex file that reproduces this problem you will make it _much_ easier for me and @romainl to analyze and pinpoint the problem.

**Comment by guiniol** [comment]
Sure. Here is a MWE:
`main.tex`
```tex
\documentclass{minimal}
\begin{document}

Hello World!
\ref{asd}

\end{document}
```
`vimrc`
```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/plugged/vimtex,' . &rtp
let &rtp .= ',~/.vim/plugged/vimtex/after'

" Load other plugins, if necessary
let &rtp  = '~/.vim/plugged/vim-qf,' . &rtp
let &rtp .= ',~/.vim/plugged/vim-qf/after'

filetype plugin indent on
syntax enable
```

With this example, when compiling, latex complains about the missing reference and opens the quickfix, which is immediately focused.

**Comment by lervag** [comment]
I've reproduced with the following minimal vimrc file:

```vim
set nocompatible
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp  = '~/.vim/bundle/vim-qf,' . &rtp
filetype plugin indent on
syntax enable

let g:vimtex_echo_ignore_wait = 1
let g:vimtex_view_automatic = 0

silent edit main.tex
```

Opening with `vim --servername VIM -u minivimrc` and then doing `\ll` reproduces the issue. If I comment out `vim-qf`, everything works. I'll look into this to see if there might be a problem (or solution) on the vimtex end.

**Comment by guiniol** [comment]
@lervag Thanks

**Comment by lervag** [comment]
It seems vim-qf fires `qf#OpenQuickfix()` on `cgetfile`. If `g:qf_auto_resize` is 1, this function closes any open quickfix window, then reopens it with `cwindow`. This does not look very good to me, because it will clearly interfere with other plugins that act on these events.

@guiniol I think one possibility is to create your own variant of vim-qf. I did that, and it is really quite simple.  [This](https://github.com/lervag/dotvim/blob/master/personal/ftplugin/qf.vim) is what I do. A different approach, but it works for me.

In any case, I don't think I want to spend more time on this, unless @romainl have some useful comments that might change my mind that I should do things differently from vimtex.

**Comment by guiniol** [comment]
@lervag Thanks for spending the time, and sorry for all the trouble!

I'll see if I can fix that or if @romainl has ideas.
Anyhow, I wasn't expecting you to change things specifically for `vim-qf`. I just wanted you to be aware of this issue in case there was a solution to know if the focus is on the quickfix and not do the `wincmd p` blindly.

**Comment by lervag** [comment]
@guiniol No problem. Btw: In vimtex I do not simply do `wincmd p`. I save the original `winnr()` and use that. It is not entirely fool proof, but it works in all cases I've seen so far.

**Comment by romainl** [comment]
Thanks, I will take a look a this issue next week-end.

Note that vim-qf is written from my point of view and well… I don't use many plugins. Without a proper plugin API, bad interactions are to be expected.

**Comment by phcerdan** [comment]
I use `vimtex` and `vim-qf`, it would be extra nice to achieve compatibility if possible. Right now I have to disable `vim-qf` when doing some heavy latex.

**Comment by guiniol** [comment]
@phcerdan setting `let g:qf_auto_open_quickfix = 0` lets vimtex handle opening the quickfix window but will still give you the other useful vim-qf features.
AFAICT, as there is no clear API for interacting with the quickfix window, every plugin has to do it its way and vim-qf and vimtex ways interact with each other when opening the quickfix window. However, there's no good way to "fix" either plugin.

**Comment by lervag** [comment]
You can also `let g:vimtex_quickfix_mode = 0` if you want to let `vim-qf` open the quickfix window. Apart from that, I agree with @guiniol that it is difficult to ensure compatibility between plugins. However, there is always room for improvement, and I might have made some bad choices. If anyone should have good suggestions for improving how vimtex interacts with the quickfix window, I'm all ears. :)

**Comment by romainl** [comment]
Thank you all for your comments but… without a proper plugin API I will simply never even try to ensure compatibility with other plugins.

Every feature in vim-qf is currently behind a toggle and I think that should be enough to deal with most annoying corner cases.

**Comment by phcerdan** [comment]
@romainl that makes sense. And thanks @guiniol @lervag, I will try those options.

**Comment by guiniol** [comment]
@lervag I thought vimtex wouldn't even try to populate the quickfix with that option. I'll have to try it.

**Comment by lervag** [comment]
@guiniol No, that option only controls whether or not to open the qf window. It is described in the docs. If set to zero, you have to open the quickfix window manually to see the errors/warnings.

**Comment by guiniol** [comment]
@lervag indeed it does. I had actually tried it now, the problem is that when vim-qf opens the qf, it puts you in the qf window (this only happens with vimtex AFAICT), so it's a bit inconvenient with autocompile on ^^

**Comment by lervag** [comment]
Ok. Then perhaps you could use `let g:qf_auto_open_quickfix = 0` instead?

**Comment by guiniol** [comment]
Yes, that's what I do. The only thing is that we don't get the autoresize from qf, but with all the overflows/underflows, I rarely have less than 10 lines of errors anyway ^^
