### ISSUE TITLE
Inverse of Filter

### ISSUE THREAD

**Issue by rgrinberg** [romainl/vim-qf#5]
Hi, I'd like something like Filter except that it would delete rather than keep matching qf entries. Vim itself both `g` and `v` so I think it's a fair request.

**Comment by romainl** [comment]
Hi, please pull 22bc9b81b2c40c0fb2ac399759c037d8cd4ecd3b.

I've added two commands: `:Keep` and `:Reject` which are less ambiguous than `:Filter`.

`:Filter` is still there, though, and works just like `:Keep`. I've modified it to take an optional `!` to make it work like `:Reject`.

There is no `:help` ATM.

**Comment by rgrinberg** [comment]
Thanks!

**Comment by romainl** [comment]
See release 0.0.7.

**Comment by rgrinberg** [comment]
Thanks. Will update.
