### ISSUE TITLE
`Reject` with an argument does not filter qf results

### ISSUE THREAD

**Issue by yevhen-m** [romainl/vim-qf#52]
`Reject` with an argument does not filter results in location list. I have to move the cursor to the word and then `Reject` without arguments works as expected.
`osx`, `nvim 0.2.0`

**Comment by romainl** [comment]
This is very likely to be a side-effect of https://github.com/romainl/vim-qf/issues/50

I'll investigate this ASAP but you should always use releases, not master.

**Comment by yevhen-m** [comment]
@romainl  thanks a lot! 

By the way, what do you mean by 
> you should always use releases, not master

?

**Comment by romainl** [comment]
I mean [this](https://github.com/romainl/vim-qf/releases).

**Comment by yevhen-m** [comment]
I've been using last release version for all this time. Has this issue been fixed?

**Comment by romainl** [comment]
Nope, that issue will be fixed in the next release. Keep using the latest release until then.

**Comment by yevhen-m** [comment]
@romainl when do you plan to make a new release? It's been almost a year since the last one.

**Comment by romainl** [comment]
The latest release is fine. Anyway, thanks for reminding me about this issue, I'm on it.

**Comment by romainl** [comment]
@yevhen-m, commit b14dcb2 seems to solve this issue. I'll put a release together once you have confirmed it.

**Comment by yevhen-m** [comment]
Looks like it's working.
