### ISSUE TITLE
qf_qf_toggle slow after mapping changes

### ISSUE THREAD

**Issue by mgoral** [romainl/vim-qf#53]
Hi,

I noticed that after commit c2596df2be746ff3393d9d97e2ec986d4ea1a67c running `<Plug>qf_qf_toggle` got really slow. It seems that vim's waiting for "something" until `timeloutlen` passes (unless it's too small): it prints `_qf_toggle` in status line and waits a second before it executes toggle. If I lower timeoutlen, it gets a little quicker, but at some point timeoutlen passes faster than I'm able to press keys (my mapping includes a \<leader\>).

I checked it with a clean .vimrc and with several mappings to exclude any mapping collisions (also checked my `:map`). I also checked it with neovim 0.1.7 and vim 8.0.550 with the same result.

I figured out a workaround however. Instead of mapping like this one:

```
nmap <leader>f <Plug>qf_qf_toggle
```

I use something like this (notice a semicolon at the end of mapping)

```
nmap <leader>f <Plug>qf_qf_toggle;
```

It makes `qf_qf_toggle` instant again.

The problem doesn't exist before that commit, when mappings with parens were correct ones.

**Comment by romainl** [comment]
OK, I'll check it out.

**Comment by romainl** [comment]
So I confirmed both the issue *and* your workaround. Do you experience that on other mappings or is it only on `<Plug>qf_qf_toggle`?

**Comment by mgoral** [comment]
Looks like the slowdown only occurs with `<Plug>qf_qf_toggle` (but not with `_stay` variant). However, I wasn't able to verify `<Plug>qf_switch`, because it didn't jump to quickfix at all (I never used this function before though, just checked it now). Other mappings work fine.

**Comment by romainl** [comment]
This is *somewhat* unexpected: what we have is an ambiguity between `qf_qf_toggle` and `qf_qf_toggle_stay`. Vim really treats `<Plug>` mappings like regular mappings, after all, waiting for further input to decide which of the two commands to execute.

The solution will be to make the name unique: `qf_qf_stay_toggle` or something like that.

**Comment by romainl** [comment]
The issue seems fixed. Thank you for your support, @mgoral.
