### ISSUE TITLE
qf_auto_open_quickfix causes post-cmd jump to occur in numerically last window

### ISSUE THREAD

**Issue by qstrahl** [romainl/vim-qf#59]
## To Reproduce

1. Make sure `g:qf_auto_open_quickfix` is `1` or unset (this is the default)
2. Split the window a few times
3. Go to the first window (or any but the last)
4. Perform any quickfix command that finds matches

## Bad Behaviour

The first result will be jumped to in the last window on the tabpage in numerical order.

## Expected Behaviour

It should jump within the window you ran the quickfix command from.

**Comment by qstrahl** [comment]
The bug does not occur if you `let g:qf_auto_open_quickfix=0`, suggesting that it is somehow related to the function responsible for automatically opening the list. Presumably, location lists have the same bad behaviour, but I haven't tested this.

**Comment by romainl** [comment]
Thanks, I will take a look at that through the week-end.

**Comment by romainl** [comment]
From `:help quickfix-window`:

    You can use ":.cc" to jump to the error under the cursor.
    Hitting the <Enter> key or double-clicking the mouse on a line has the same
    effect.  The file containing the error is opened in the window above the
    quickfix window.  […]

So this doesn't look like a bug after all. If you still want `<CR>` to open the error in the previous window I might be able to cook up a custom mapping, though.

**Comment by qstrahl** [comment]
WHAAAT. I never would have guessed that was default behaviour... fuck me I guess. Personally, I wouldn't want to go so far as to make mappings that change the default behaviour, however unintuitive I find it... sorry for wasting your time :<
