### ISSUE TITLE
g:qf_max_height is ignored when g:qf_auto_open_quickfix is 0

### ISSUE THREAD

**Issue by mdsn** [romainl/vim-qf#61]
Set `g:qf_max_height = 3`, and `g:qf_auto_open_quickfix = 0`. Run a make command or something that populates the quickfix window. Open it up with the key mapped to `<Plug>QfCtoggle`, the quickfix window has height 10 (default). It should observe the max_height value.

Leave `g:qf_auto_open_quickfix` on its default value of 1, and the quickfix window will (automatically) be opened with the correct height.

**Comment by RobertBuhren** [comment]
Related to this:

The `let g:qf_auto_resize ` option does only work in the case the quickfix window was opened automatically.  When opening it using `<Plug>(qf_qf_toggle)` the quickfix windows height is set to the default again regardless of the number of items in the quickfix list.
