### ISSUE TITLE
Override nowrap

### ISSUE THREAD

**Issue by FabioAntunes** [romainl/vim-qf#63]
It would be possible to extract the wrap into a variable so we can make it optional?

even though I have this on my config:
```
autocmd FileType qf setlocal wrap linebreak
```

I prefer having quickfix windows per buffer, it makes it easier to understand where do I have linter errors. But without the linebreak they become a bit useless when I have multiple buffers open.

![screen shot 2018-01-25 at 11 09 54](https://user-images.githubusercontent.com/2544673/35385496-698d2a2e-01c0-11e8-8382-3aff1f13c23e.png)

**Comment by romainl** [comment]
Please try [branch issue#63](https://github.com/romainl/vim-qf/tree/issue%2363).

**Comment by FabioAntunes** [comment]
Been using that branch and so far it's been working fine, thanks for the quick response on this.

**Comment by romainl** [comment]
Good to hear. I'll merge that branch into master but I don't think I will push a new release right away.
