### ISSUE TITLE
Plugin prevents vertical opening of quickfix

### ISSUE THREAD

**Issue by ajcrites** [romainl/vim-qf#67]
With this plugin enabled, if I run `:vert copen` it opens the quickfix window horizontally and it takes up the whole screen. Just using `copen` still opens it vertically, but normally.

I'm still able to make this window vertical using <kbd>Ctrl-W</kbd><kbd>L</kbd>.

**Comment by romainl** [comment]
Did you notice [these two options](https://github.com/romainl/vim-qf/blob/master/doc/qf.txt#L233-L252).

**Comment by ajcrites** [comment]
Those options help in some cases, but you still don't seem to have the ability to open vertical buffers if the options are disabled while still having horizontal quickfixes.

Interestingly with the `qf*_window_bottom` option on, the quickfix no longer closes automatically when I close the parent buffer. This could be a separate issue, though.

**Comment by nomasprime** [comment]
@romainl is there a way to open the quickfix automatically in a vertical split?

**Comment by romainl** [comment]
@nomasprime I think adding something like:

    wincmd L

to `after/ftplugin/qf.vim` should do the trick.

**Comment by nomasprime** [comment]
@romainl thanks. Thinking about it I'd like to try having the location and quickfix lists stacked in the same vertical split to maximise screen space. Any ideas?

**Comment by romainl** [comment]
@nomasprime, it's probably doable, via an autocommand that:

1. fires on the `qf` filetype,
2. figures out what quickfix and/or location window are opened,
3. creates the desired layout.

But it doesn't seem trivial.

**Comment by nomasprime** [comment]
@romainl cool, thanks for the pointers. I'll come back to it when I have some spare time.
