### ISSUE TITLE
save and restore quickfix window state on toggle

### ISSUE THREAD

**Issue by balta2ar** [romainl/vim-qf#71]
Hello. I have the following option in my vimrc:
```
let g:qf_save_win_view = 1
```
However, when I use `qf_qf_toggle`, quickfix window state is not saved. Specifically, is it possible to:
1) save and restore quickfix window size?
2) save and restore cursor position within the quickfix window (line and column)?

Thank you.

**Comment by romainl** [comment]
This seems to work correctly now.
