### ISSUE TITLE
Please make qf#filegroup#NextFile() / qf#filegroup#PreviousFile() mappings optional

### ISSUE THREAD

**Issue by promisedlandt** [romainl/vim-qf#74]
The `{` / `}` buffer local mappings are currently not optional, I would like them to be :)
There is already a comment `" TODO: allow customization` there, so I'm guessing you already have something planned, but I couldn't find an issue.

I tried to convert them to plugin mappings like so:

````
nmap         <Plug>(qf_fg_next_file)     :<C-u> call qf#filegroup#NextFile()<CR>                                                                                                 
nmap         <Plug>(qf_fg_previous_file)         :<C-u> call qf#filegroup#PreviousFile()<CR> 
````

but couldn't get them to work after that - possibly because they're defined in `after`? I don't know enough vimscript to fix it.

Personally, I prefer for plugins to make no key bindings, but offer me the opportunity to make my own.

**Comment by romainl** [comment]
> Personally, I prefer for plugins to make no key bindings, but offer me the opportunity to make my own.

I completely agree.

I've already thought about it but found that `<Plug>` mappings don't play well with filetype stuff. Thanks for reminding me about that flaw.

**Comment by romainl** [comment]
@promisedlandt, @flemingfleming, could you try branch issue#74, please?

**Comment by flemingfleming** [comment]
Works fine so far for me, but it does prevent the user mapping any other custom functionality to whichever keys they choose.

I also wonder about the performance impact of getting and filtering the list of every nmap everytime we call the mapping outside a quickfix window. Vim handles it fine for me, but there might be problems for people with more mappings/slow hardware.

**Comment by romainl** [comment]
> but it does prevent the user mapping any other custom functionality to whichever keys they choose.

I wrote it in such a way that the shortcut chosen by the user is played back as-is when not in a quickfix window. Did you have a remapping problem?

> I also wonder about the performance impact of getting and filtering the list of every nmap everytime we call the mapping outside a quickfix window. Vim handles it fine for me, but there might be problems for people with more mappings/slow hardware.

I tested it in a slow Ubuntu VM without unexpected performance issue. I'll wait until someone complains.

> architecture

I hate it when plugins show their guts or ask unreasonable coding from their users. In the absence of an actual mapping clash I think I will stick with those two `<Plug>` mappings.

**Comment by romainl** [comment]
Or I could simply use the same method as with the Ack mappings: hide the feature behind a global variable. Something like:

    let qf_filegroup_maps = ['{', '}']

This would allow me to keep the mappings in `after/ftplugin/qf.vim` and thus:

* return them to their previous simplicity,
* avoid clashing with user-defined mappings.

I'd prefer exposing `<Plug>` mappings but this seems like an acceptable compromise.

**Comment by promisedlandt** [comment]
Sorry to say it doesn't work for well for me.

I have `[[` and `]]` mapped to indent level movement (with [IndentWise](https://github.com/jeetsukumaran/vim-indentwise)), and I tried your new mappings with it:

`nmap ]] <Plug>(qf_next_file)` (`[[` analogous)

Expected result: in quickfix / loclist, `qf_(next|previous)_file`, in all other filetypes, indent level movement.
Actual result: quickfix / loclist work das expected, but in other filetypes, `[[` reverts back to vim builtin `[[`.

Makes sense of course - I overwrite my original mapping with the vim-qf one.

The solution from @flemingfleming with augroup should work for my usecase, and is, in my opinion, reasonable to ask of a user.  
I think very few people remember all the names of the plugin provided mappings, they check the help and copy from there anyway - letting them copy a 6 line block instead of 2 mappings will not be huge issue.

**Comment by romainl** [comment]
@promisedlandt, @flemingfleming, can you try again? I didn't update the README and doc but it's easy to test; just add these two lines to your `virmc`:

    let g:qf_mapping_filegroup_previous = '{'
    let g:qf_mapping_filegroup_next = '}'

**Comment by promisedlandt** [comment]
Thank you, that works perfectly for my use case!

**Comment by flemingfleming** [comment]
The reason I advocated the lower level approach was that it allows less customisation than a plug mapping. For example, with a plug mapping there's the freedom to compose mappings like this, amongst other things.

    autocmd Vimrc Filetype qf
                \  nmap <buffer> ) <plug>(qf_fg_next_file)
                \| nmap <buffer> ( <plug>(qf_fg_previous_file)
                \| nmap <buffer> } <plug>(qf_fg_next_file)o
                \| nmap <buffer> { <plug>(qf_fg_previous_file)o

Also adding nowait does have the disadvantage that someone might actually want vim to wait for them to complete a multicharacter mapping (though I haven't ever seen an example), With a plug mapping you can add the `<nowait.>` yourself (although you'd still probably have to document that).

**Comment by romainl** [comment]
Done.

**Comment by promisedlandt** [comment]
Looks great, thanks!
