### ISSUE TITLE
LoadList only loads list in the quickfix list

### ISSUE THREAD

**Issue by romainl** [romainl/vim-qf#76]
**ggVGc** hello romainl

**ggVGc** I've been waiting for you

**romainl** *panic*

**ggVGc** romainl: it seems to me vim-qf LoadList doesn't work like it should with loclist? Not sure if it's a bug or me misunderstanding. I can use SaveList in a loclist, and load it in quickfix, but if I load inside a loclist, it seems it loads into quickfix anyway?

**ggVGc** am I doing something wrong or is it a bug?

**romainl** it should be transparent

**romainl** sounds like a bug

**ggVGc** romainl: so, it should be reproducable like this: Put stuff in loclist, use SaveList, do something (like Reject xxx), use LoadList. loclist now clears, and content gets loaded in quickfix

**ggVGc** at least forme

**ggVGc** reproducible*

**romainl** definitely a bug

**Comment by lacygoill** [comment]
This patch should fix the issue:
```diff
diff --git a/after/ftplugin/qf.vim b/after/ftplugin/qf.vim
index ddab68c..c28f43d 100644
--- a/after/ftplugin/qf.vim
+++ b/after/ftplugin/qf.vim
@@ -38,7 +38,7 @@ else
 endif
 
 " are we in a location list or a quickfix list?
-let b:qf_isLoc = !empty(getloclist(0))
+let b:qf_isLoc = get(get(getwininfo(win_getid()), 0, {}), 'loclist', 0)
 
 " customize the statusline
 if exists("g:qf_statusline")
diff --git a/autoload/qf.vim b/autoload/qf.vim
index 9bc9d2c..938e301 100644
--- a/autoload/qf.vim
+++ b/autoload/qf.vim
@@ -96,6 +96,10 @@ function! qf#SetList(newlist, ...)
     " call partial with optional arguments
     call call(Func, a:000)
 
+    if a:newlist == []
+        return
+    endif
+
     if get(b:, 'qf_isLoc', 0)
         execute get(g:, "qf_auto_resize", 1) ? 'lclose|' . min([ max_height, len(getloclist(0)) ]) . 'lwindow' : 'lwindow'
     else
```

**Comment by romainl** [comment]
@lacygoill would you consider making a PR?
