### ISSUE TITLE
When g:qf_auto_resize = 0 Vim won't move focus to quickfix window when already open

### ISSUE THREAD

**Issue by bfrg** [romainl/vim-qf#79]
When `g:qf_auto_resize = 0` Vim won't move the focus to the quickfix (or location list) window after running a quickfix command, while the quickfix window is already open. It does move the focus when `g:qf_auto_resize = 1` because in this case `cclose` (or `lclose`) are called before `cwindow` (or `lwindow`).

I think the fix is simple, just do the same thing as for `g:qf_auto_resize = 1` and call `cclose` before `cwindow`.

**Comment by romainl** [comment]
Fixed.
