### ISSUE TITLE
Consider adding :colder / :cnewer mappings

### ISSUE THREAD

**Issue by jparise** [romainl/vim-qf#83]
In ["Colder quickfix lists"](https://vimways.org/2018/colder-quickfix-lists/), the author makes the case for convenience mappings around `:colder` / `:cnewer`. Those could make nice additions to vim-qf.

**Comment by romainl** [comment]
I agree. This shouldn't be too hard but I'm very busy these days so I won't try my hands at it before next month.

If you feel like making a PR…
