### ISSUE TITLE
How to map an autocmd to filter quickfix to the current buffer

### ISSUE THREAD

**Issue by ABitMoreDepth** [romainl/vim-qf#87]
Is there a way to map the equivalent of `Keep bufname('%')` to execute every time the quickfix list is updated by my language client?

Apologies, I'm not very familiar with vimscript, but I'm guessing I'd need an `autocmd` bound to whatever the quickfix event would be, that runs the function behind `Keep` with an argument supplied by `bufname('%')` as if it were run from the currently open buffer, if that makes sense?

I don't know whether something like that would be a popular built-in command?

Effectively I want to be able to automatically see only quickfix entries related to the current buffer, and for that to remain the case when the quickfix is re-populated.

Thanks so much for the work you've already done with this plugin, and apologies if I've missed something obvious before posting this!

**Comment by romainl** [comment]
In my opinion, your language client should deal with other files in your project only when told to. If linting (or whatever) the current file gives you problems located in other files then there's a gross design issue in your language client (or server).

That said, the only event I could think of is `:help QuickFixCmdPost` which is at the core of this plugin. Using it on your end is very likely to cause sync issues.

Let me see if I can provide a reasonably abstracted "hooks" mechanism.

**Comment by ABitMoreDepth** [comment]
I'd happen to agree with you re this being a linter issue, though the maintainer of the language client that I'm using disagrees (for whatever reason).

I'm getting by ok with this plugin's existing functionality, so whilst hooks would be great, and I'd be happy to test for you, by all means feel free to work on any higher priority bits as you see fit.

Thanks for getting back to me. :)
